/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class AccountShutdownParam {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AccountShutdownParam(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AccountShutdownParam obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(AccountShutdownParam obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_AccountShutdownParam(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setForce(boolean value) {
    pjsua2JNI.AccountShutdownParam_force_set(swigCPtr, this, value);
  }

  public boolean getForce() {
    return pjsua2JNI.AccountShutdownParam_force_get(swigCPtr, this);
  }

  public AccountShutdownParam() {
    this(pjsua2JNI.new_AccountShutdownParam(), true);
  }

}
