/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class AudioMediaAiPort extends AudioMedia {
  private transient long swigCPtr;

  protected AudioMediaAiPort(long cPtr, boolean cMemoryOwn) {
    super(pjsua2JNI.AudioMediaAiPort_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AudioMediaAiPort obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(AudioMediaAiPort obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_AudioMediaAiPort(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    pjsua2JNI.AudioMediaAiPort_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    pjsua2JNI.AudioMediaAiPort_change_ownership(this, swigCPtr, true);
  }

  @SuppressWarnings("this-escape")
  public AudioMediaAiPort() {
    this(pjsua2JNI.new_AudioMediaAiPort(), true);
    pjsua2JNI.AudioMediaAiPort_director_connect(this, swigCPtr, true, true);
  }

  public void createPort(AiMediaPortParam prm) throws java.lang.Exception {
    pjsua2JNI.AudioMediaAiPort_createPort__SWIG_0(swigCPtr, this, AiMediaPortParam.getCPtr(prm), prm);
  }

  public void createPort() throws java.lang.Exception {
    pjsua2JNI.AudioMediaAiPort_createPort__SWIG_1(swigCPtr, this);
  }

  public void connect(String url, String authToken) throws java.lang.Exception {
    pjsua2JNI.AudioMediaAiPort_connect(swigCPtr, this, url, authToken);
  }

  public void disconnect() throws java.lang.Exception {
    pjsua2JNI.AudioMediaAiPort_disconnect(swigCPtr, this);
  }

  public void onEvent(AiMediaEvent event) {
    if (getClass() == AudioMediaAiPort.class) pjsua2JNI.AudioMediaAiPort_onEvent(swigCPtr, this, AiMediaEvent.getCPtr(event), event); else pjsua2JNI.AudioMediaAiPort_onEventSwigExplicitAudioMediaAiPort(swigCPtr, this, AiMediaEvent.getCPtr(event), event);
  }

}
