/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class AudioMediaConnectInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AudioMediaConnectInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AudioMediaConnectInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(AudioMediaConnectInfo obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_AudioMediaConnectInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMediaId(long value) {
    pjsua2JNI.AudioMediaConnectInfo_mediaId_set(swigCPtr, this, value);
  }

  public long getMediaId() {
    return pjsua2JNI.AudioMediaConnectInfo_mediaId_get(swigCPtr, this);
  }

  public void setTargetMediaId(long value) {
    pjsua2JNI.AudioMediaConnectInfo_targetMediaId_set(swigCPtr, this, value);
  }

  public long getTargetMediaId() {
    return pjsua2JNI.AudioMediaConnectInfo_targetMediaId_get(swigCPtr, this);
  }

  public void setAdjLevel(int value) {
    pjsua2JNI.AudioMediaConnectInfo_adjLevel_set(swigCPtr, this, value);
  }

  public int getAdjLevel() {
    return pjsua2JNI.AudioMediaConnectInfo_adjLevel_get(swigCPtr, this);
  }

  public AudioMediaConnectInfo() {
    this(pjsua2JNI.new_AudioMediaConnectInfo(), true);
  }

}
