/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class AuthChallenge {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AuthChallenge(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AuthChallenge obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(AuthChallenge obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_AuthChallenge(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AuthChallenge() {
    this(pjsua2JNI.new_AuthChallenge(), true);
  }

  public AuthChallenge defer() throws java.lang.Exception {
    long cPtr = pjsua2JNI.AuthChallenge_defer(swigCPtr, this);
    return (cPtr == 0) ? null : new AuthChallenge(cPtr, true);
  }

  public int respond() {
    return pjsua2JNI.AuthChallenge_respond__SWIG_0(swigCPtr, this);
  }

  public int respond(AuthCredInfoVector creds) {
    return pjsua2JNI.AuthChallenge_respond__SWIG_1(swigCPtr, this, AuthCredInfoVector.getCPtr(creds), creds);
  }

  public int abandon() {
    return pjsua2JNI.AuthChallenge_abandon(swigCPtr, this);
  }

  public boolean isValid() {
    return pjsua2JNI.AuthChallenge_isValid(swigCPtr, this);
  }

}
