/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class CallSendTextParam {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CallSendTextParam(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CallSendTextParam obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CallSendTextParam obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_CallSendTextParam(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMedIdx(int value) {
    pjsua2JNI.CallSendTextParam_medIdx_set(swigCPtr, this, value);
  }

  public int getMedIdx() {
    return pjsua2JNI.CallSendTextParam_medIdx_get(swigCPtr, this);
  }

  public void setText(String value) {
    pjsua2JNI.CallSendTextParam_text_set(swigCPtr, this, value);
  }

  public String getText() {
    return pjsua2JNI.CallSendTextParam_text_get(swigCPtr, this);
  }

  public CallSendTextParam() {
    this(pjsua2JNI.new_CallSendTextParam(), true);
  }

}
