/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class CodecLyraConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CodecLyraConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CodecLyraConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CodecLyraConfig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_CodecLyraConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBitRate(long value) {
    pjsua2JNI.CodecLyraConfig_bitRate_set(swigCPtr, this, value);
  }

  public long getBitRate() {
    return pjsua2JNI.CodecLyraConfig_bitRate_get(swigCPtr, this);
  }

  public void setModelPath(String value) {
    pjsua2JNI.CodecLyraConfig_modelPath_set(swigCPtr, this, value);
  }

  public String getModelPath() {
    return pjsua2JNI.CodecLyraConfig_modelPath_get(swigCPtr, this);
  }

  public CodecLyraConfig() {
    this(pjsua2JNI.new_CodecLyraConfig(), true);
  }

}
