/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class OnAuthChallengeParam {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OnAuthChallengeParam(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OnAuthChallengeParam obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(OnAuthChallengeParam obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_OnAuthChallengeParam(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAccId(int value) {
    pjsua2JNI.OnAuthChallengeParam_accId_set(swigCPtr, this, value);
  }

  public int getAccId() {
    return pjsua2JNI.OnAuthChallengeParam_accId_get(swigCPtr, this);
  }

  public void setCallId(int value) {
    pjsua2JNI.OnAuthChallengeParam_callId_set(swigCPtr, this, value);
  }

  public int getCallId() {
    return pjsua2JNI.OnAuthChallengeParam_callId_get(swigCPtr, this);
  }

  public void setRdata(SipRxData value) {
    pjsua2JNI.OnAuthChallengeParam_rdata_set(swigCPtr, this, SipRxData.getCPtr(value), value);
  }

  public SipRxData getRdata() {
    long cPtr = pjsua2JNI.OnAuthChallengeParam_rdata_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SipRxData(cPtr, false);
  }

  public AuthChallenge getChallenge() {
    long cPtr = pjsua2JNI.OnAuthChallengeParam_challenge_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AuthChallenge(cPtr, false);
  }

  public OnAuthChallengeParam() {
    this(pjsua2JNI.new_OnAuthChallengeParam(), true);
  }

}
