/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class SockOpt {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SockOpt(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SockOpt obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SockOpt obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_SockOpt(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLevel(int value) {
    pjsua2JNI.SockOpt_level_set(swigCPtr, this, value);
  }

  public int getLevel() {
    return pjsua2JNI.SockOpt_level_get(swigCPtr, this);
  }

  public void setOptName(int value) {
    pjsua2JNI.SockOpt_optName_set(swigCPtr, this, value);
  }

  public int getOptName() {
    return pjsua2JNI.SockOpt_optName_get(swigCPtr, this);
  }

  public SockOpt() {
    this(pjsua2JNI.new_SockOpt__SWIG_0(), true);
  }

  public SockOpt(int level, int optName, int optVal) {
    this(pjsua2JNI.new_SockOpt__SWIG_1(level, optName, optVal), true);
  }

  public void setOptValInt(int opt_val) {
    pjsua2JNI.SockOpt_setOptValInt(swigCPtr, this, opt_val);
  }

}
