/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class VideoRecorder {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VideoRecorder(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VideoRecorder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(VideoRecorder obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_VideoRecorder(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    pjsua2JNI.VideoRecorder_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    pjsua2JNI.VideoRecorder_change_ownership(this, swigCPtr, true);
  }

  @SuppressWarnings("this-escape")
  public VideoRecorder() {
    this(pjsua2JNI.new_VideoRecorder(), true);
    pjsua2JNI.VideoRecorder_director_connect(this, swigCPtr, true, true);
  }

  public void createVideoRecorder(String file_name, int max_size, MediaFormatVideo vid_fmt, MediaFormatAudio aud_fmt, long options) throws java.lang.Exception {
    pjsua2JNI.VideoRecorder_createVideoRecorder__SWIG_0(swigCPtr, this, file_name, max_size, MediaFormatVideo.getCPtr(vid_fmt), vid_fmt, MediaFormatAudio.getCPtr(aud_fmt), aud_fmt, options);
  }

  public void createVideoRecorder(String file_name, int max_size, MediaFormatVideo vid_fmt, MediaFormatAudio aud_fmt) throws java.lang.Exception {
    pjsua2JNI.VideoRecorder_createVideoRecorder__SWIG_1(swigCPtr, this, file_name, max_size, MediaFormatVideo.getCPtr(vid_fmt), vid_fmt, MediaFormatAudio.getCPtr(aud_fmt), aud_fmt);
  }

  public void createVideoRecorder(String file_name, int max_size, MediaFormatVideo vid_fmt) throws java.lang.Exception {
    pjsua2JNI.VideoRecorder_createVideoRecorder__SWIG_2(swigCPtr, this, file_name, max_size, MediaFormatVideo.getCPtr(vid_fmt), vid_fmt);
  }

  public void createVideoRecorder(String file_name, int max_size) throws java.lang.Exception {
    pjsua2JNI.VideoRecorder_createVideoRecorder__SWIG_3(swigCPtr, this, file_name, max_size);
  }

  public void createVideoRecorder(String file_name) throws java.lang.Exception {
    pjsua2JNI.VideoRecorder_createVideoRecorder__SWIG_4(swigCPtr, this, file_name);
  }

  public VideoMedia getVideoMedia() throws java.lang.Exception {
    return new VideoMedia(pjsua2JNI.VideoRecorder_getVideoMedia(swigCPtr, this), true);
  }

  public AudioMedia getAudioMedia() throws java.lang.Exception {
    return new AudioMedia(pjsua2JNI.VideoRecorder_getAudioMedia(swigCPtr, this), true);
  }

  public void onMaxSize() {
    if (getClass() == VideoRecorder.class) pjsua2JNI.VideoRecorder_onMaxSize(swigCPtr, this); else pjsua2JNI.VideoRecorder_onMaxSizeSwigExplicitVideoRecorder(swigCPtr, this);
  }

}
