/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class VideoMediaOpParam {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VideoMediaOpParam(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VideoMediaOpParam obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(VideoMediaOpParam obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_VideoMediaOpParam(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAddInfo(VideoMediaAddInfo value) {
    pjsua2JNI.VideoMediaOpParam_addInfo_set(swigCPtr, this, VideoMediaAddInfo.getCPtr(value), value);
  }

  public VideoMediaAddInfo getAddInfo() {
    long cPtr = pjsua2JNI.VideoMediaOpParam_addInfo_get(swigCPtr, this);
    return (cPtr == 0) ? null : new VideoMediaAddInfo(cPtr, false);
  }

  public void setRemoveInfo(VideoMediaRemoveInfo value) {
    pjsua2JNI.VideoMediaOpParam_removeInfo_set(swigCPtr, this, VideoMediaRemoveInfo.getCPtr(value), value);
  }

  public VideoMediaRemoveInfo getRemoveInfo() {
    long cPtr = pjsua2JNI.VideoMediaOpParam_removeInfo_get(swigCPtr, this);
    return (cPtr == 0) ? null : new VideoMediaRemoveInfo(cPtr, false);
  }

  public void setConnectInfo(VideoMediaConnectInfo value) {
    pjsua2JNI.VideoMediaOpParam_connectInfo_set(swigCPtr, this, VideoMediaConnectInfo.getCPtr(value), value);
  }

  public VideoMediaConnectInfo getConnectInfo() {
    long cPtr = pjsua2JNI.VideoMediaOpParam_connectInfo_get(swigCPtr, this);
    return (cPtr == 0) ? null : new VideoMediaConnectInfo(cPtr, false);
  }

  public void setDisconnectInfo(VideoMediaDisconnectInfo value) {
    pjsua2JNI.VideoMediaOpParam_disconnectInfo_set(swigCPtr, this, VideoMediaDisconnectInfo.getCPtr(value), value);
  }

  public VideoMediaDisconnectInfo getDisconnectInfo() {
    long cPtr = pjsua2JNI.VideoMediaOpParam_disconnectInfo_get(swigCPtr, this);
    return (cPtr == 0) ? null : new VideoMediaDisconnectInfo(cPtr, false);
  }

  public void setUpdateInfo(VideoMediaUpdateInfo value) {
    pjsua2JNI.VideoMediaOpParam_updateInfo_set(swigCPtr, this, VideoMediaUpdateInfo.getCPtr(value), value);
  }

  public VideoMediaUpdateInfo getUpdateInfo() {
    long cPtr = pjsua2JNI.VideoMediaOpParam_updateInfo_get(swigCPtr, this);
    return (cPtr == 0) ? null : new VideoMediaUpdateInfo(cPtr, false);
  }

  public VideoMediaOpParam() {
    this(pjsua2JNI.new_VideoMediaOpParam(), true);
  }

}
