package com.whatsappv2.data.calllog.db

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * One finished call, flattened for SQLite (Task 47, §5.2).
 *
 * ## Identity
 *
 * An autogenerated row id rather than the engine's `CallId`. A `CallId` is a UUID the
 * stack minted for one dialog and is not reproducible after a restart, so it makes a
 * poor key for a table that outlives the process; it is not stored at all, because
 * nothing reads a log entry by it.
 *
 * ## Denormalised on purpose
 *
 * [contactName] is a copy of what the address book said at the time, not a join to it.
 * A call log is a record of what happened, and re-resolving it later would rewrite
 * history every time a contact is renamed or deleted — the entry for a call from someone
 * since removed would silently become an entry from an unknown number.
 *
 * ## Indices
 *
 * [started_at_epoch_millis] carries one because every read is ordered by it, and the
 * missed-call filter has a composite covering the two columns it tests together. The
 * screen is paged over ten thousand rows (Task 48); a scan per page is the difference
 * between a list that scrolls and one that stutters.
 */
@Entity(
    tableName = "call_log",
    indices = [
        Index(value = ["started_at_epoch_millis"]),
        Index(value = ["direction", "answered_at_epoch_millis"]),
    ],
)
data class CallLogEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0L,

    @ColumnInfo(name = "account_id")
    val accountId: String,

    /** The far end, rendered. Re-parsed on the way out, as the account table does. */
    @ColumnInfo(name = "remote_uri")
    val remoteUri: String,

    /** What the peer called itself, or null when it sent no display name. */
    @ColumnInfo(name = "remote_display_name")
    val remoteDisplayName: String?,

    /** What the address book called it when the call happened, or null (Task 49). */
    @ColumnInfo(name = "contact_name")
    val contactName: String?,

    /** [com.whatsappv2.domain.engine.CallDirection], by name. */
    @ColumnInfo(name = "direction")
    val direction: String,

    @ColumnInfo(name = "started_at_epoch_millis")
    val startedAtEpochMillis: Long,

    /** Null for a call that never connected — which is what makes "missed" a fact. */
    @ColumnInfo(name = "answered_at_epoch_millis")
    val answeredAtEpochMillis: Long?,

    @ColumnInfo(name = "ended_at_epoch_millis")
    val endedAtEpochMillis: Long,

    /** [com.whatsappv2.domain.model.HangupReason], by name. */
    @ColumnInfo(name = "reason")
    val reason: String,

    /**
     * The two halves of [com.whatsappv2.domain.model.MediaProfile], separately.
     *
     * Not a token like "AUDIO_VIDEO": MediaProfile is a pair of flags rather than an
     * enum, so a token would be a second vocabulary to keep in step with it, and a call
     * that was video-only would have nowhere to go.
     */
    @ColumnInfo(name = "has_audio")
    val hasAudio: Boolean,

    @ColumnInfo(name = "has_video")
    val hasVideo: Boolean,
)
